#Dane Halle (dmh148)
#This was something I was planning on adding implementation for later.
#Basically before each level this would show and then the level would start.

.globl preLevels
.globl pre1
.globl pre2
.globl pre3

.data
preLevels:
pre1:
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"     xx        xxxxxxxx  xxx        xxx  xxxxxxxx  xx           "
	.ascii	"     xx        xxxxxxxx  xxx        xxx  xxxxxxxx  xx           "
	.ascii	"     xx        xx         xxx      xxx   xx        xx           "
	.ascii	"     xx        xx         xxx      xxx   xx        xx           "
	.ascii	"     xx        xxxxx       xxx    xxx    xxxxxx    xx           "
	.ascii	"     xx        xx          xxx    xxx    xx        xx           "
	.ascii	"     xx        xx           xxx  xxx     xx        xx           "
	.ascii	"     xxxxxxxx  xxxxxxxx      xxxxxx      xxxxxxxx  xxxxxxxx     "
	.ascii	"     xxxxxxxx  xxxxxxxx       xxxx       xxxxxxxx  xxxxxxxx     "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                              xxxxx                             "
	.ascii	"                             xxxxxx                             "
	.ascii	"                            xxxxxxx                             "
	.ascii	"                            xxxxxxx                             "
	.ascii	"                            xxxxxxx                             "
	.ascii	"                              xxxxx                             "
	.ascii	"                              xxxxx                             "
	.ascii	"                              xxxxx                             "
	.ascii	"                              xxxxx                             "
	.ascii	"                              xxxxx                             "
	.ascii	"                              xxxxx                             "
	.ascii	"                              xxxxx                             "
	.ascii	"                              xxxxx                             "
	.ascii	"                              xxxxx                             "
	.ascii	"                              xxxxx                             "
	.ascii	"                              xxxxx                             "
	.ascii	"                         xxxxxxxxxxxxxxx                        "
	.ascii	"                         xxxxxxxxxxxxxxx                        "
	.ascii	"                         xxxxxxxxxxxxxxx                        "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
pre2:
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"     xx        xxxxxxxx  xxx        xxx  xxxxxxxx  xx           "
	.ascii	"     xx        xxxxxxxx  xxx        xxx  xxxxxxxx  xx           "
	.ascii	"     xx        xx         xxx      xxx   xx        xx           "
	.ascii	"     xx        xx         xxx      xxx   xx        xx           "
	.ascii	"     xx        xxxxx       xxx    xxx    xxxxxx    xx           "
	.ascii	"     xx        xx          xxx    xxx    xx        xx           "
	.ascii	"     xx        xx           xxx  xxx     xx        xx           "
	.ascii	"     xxxxxxxx  xxxxxxxx      xxxxxx      xxxxxxxx  xxxxxxxx     "
	.ascii	"     xxxxxxxx  xxxxxxxx       xxxx       xxxxxxxx  xxxxxxxx     "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                             xxxxx                              "
	.ascii	"                           xxxxxxxxx                            "
	.ascii	"                         xxxxxxxxxxxxx                          "
	.ascii	"                       xxxxxxx   xxxxxxx                        "
	.ascii	"                     xxxxxx       xxxxxxx                       "
	.ascii	"                     xxxxxxx       xxxxxx                       "
	.ascii	"                                  xxxxxx                        "
	.ascii	"                                xxxxxxx                         "
	.ascii	"                              xxxxxx                            "
	.ascii	"                            xxxxxx                              "
	.ascii	"                          xxxxxx                                "
	.ascii	"                        xxxxxx                                  "
	.ascii	"                      xxxxxxxxxxxxxxxxxxx                       "
	.ascii	"                      xxxxxxxxxxxxxxxxxxx                       "
	.ascii	"                      xxxxxxxxxxxxxxxxxxx                       "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
pre3:
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"     xx        xxxxxxxx  xxx        xxx  xxxxxxxx  xx           "
	.ascii	"     xx        xxxxxxxx  xxx        xxx  xxxxxxxx  xx           "
	.ascii	"     xx        xx         xxx      xxx   xx        xx           "
	.ascii	"     xx        xx         xxx      xxx   xx        xx           "
	.ascii	"     xx        xxxxx       xxx    xxx    xxxxxx    xx           "
	.ascii	"     xx        xx          xxx    xxx    xx        xx           "
	.ascii	"     xx        xx           xxx  xxx     xx        xx           "
	.ascii	"     xxxxxxxx  xxxxxxxx      xxxxxx      xxxxxxxx  xxxxxxxx     "
	.ascii	"     xxxxxxxx  xxxxxxxx       xxxx       xxxxxxxx  xxxxxxxx     "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                             xxxxx                              "
	.ascii	"                           xxxxxxxxx                            "
	.ascii	"                         xxxxxxxxxxxxx                          "
	.ascii	"                       xxxxxxx   xxxxxxx                        "
	.ascii	"                     xxxxxx       xxxxxxx                       "
	.ascii	"                     xxxxxxx       xxxxxx                       "
	.ascii	"                                  xxxxxx                        "
	.ascii	"                                xxxxxxx                         "
	.ascii	"                               xxxxxxx                          "
	.ascii	"                                xxxxxxx                         "
	.ascii	"                                  xxxxxx                        "
	.ascii	"                     xxxxxxx       xxxxxx                       "
	.ascii	"                     xxxxxx       xxxxxxx                       "
	.ascii	"                       xxxxxxx   xxxxxxx                        "
	.ascii	"                         xxxxxxxxxxxxx                          "
	.ascii	"                           xxxxxxxxx                            "
	.ascii	"                             xxxxx                              "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
	.ascii	"                                                                "
