#Dane Halle (dmh148)

.globl levels
.globl level1
.globl level2
.globl level3

.data
levels:
level1:
	.ascii	"                                                                "
	.ascii  "                                                                "
	.ascii  "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   "
	.ascii  "   x                           xx                           x   "
	.ascii	"   x                           xx                           x   "
	.ascii  "   x                           xx                           x   "
	.ascii  "   x                           xx                           x   "
	.ascii  "   x                           xx                           x   "
	.ascii	"                 x                            x                 "
	.ascii  "                 x                            x                 "
	.ascii  "                 x                            x                 "
	.ascii  "                 x                            x                 "
	.ascii	"                 x                            x                 "
	.ascii  "                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 "
	.ascii  "                                                                "
	.ascii  "                                                                "
	.ascii	"                               s                                "
	.ascii  "                                                                "
	.ascii  "                                                                "
	.ascii  "                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 "
	.ascii	"                 x                            x                 "
	.ascii  "                 x                            x                 "
	.ascii  "                 x                            x                 "
	.ascii  "                 x                            x                 "
	.ascii	"                 x                            x                 "
	.ascii  "                               xx                               "
	.ascii  "                               xx                               "
	.ascii  "                               xx                               "
	.ascii	"                               xx                               "
	.ascii  "                          xxxxxxxxxxxx                          "
	.ascii  "                          d          D                          "
	.ascii  "                          d          D                          "
	.ascii	"                          d          D                          "
	.ascii  "                          d          D                          "
	.ascii  "                          xxxxxxxxxxxx                          "
	.ascii  "                               xx                               "
	.ascii	"                               xx                               "
	.ascii  "                               xx                               "
	.ascii  "                               xx                               "
	.ascii  "                 x                            x                 "
	.ascii	"                 x                            x                 "
	.ascii  "                 x                            x                 "
	.ascii  "                 x                            x                 "
	.ascii  "                 x                            x                 "
	.ascii	"                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 "
	.ascii  "                                                                "
	.ascii  "                                                                "
	.ascii  "                                                                "
	.ascii	"                                                                "
	.ascii  "                                                                "
	.ascii  "                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 "
	.ascii  "                 x                            x                 "
	.ascii	"                 x                            x                 "
	.ascii  "                 x                            x                 "
	.ascii  "                 x                            x                 "
	.ascii  "                 x                            x                 "
	.ascii	"   x                           xx                               "
	.ascii  "   x                           xx                           x   "
	.ascii  "   x                           xx                           x   "
	.ascii  "   x                           xx                           x   "
	.ascii	"   x                           xx                           x   "
	.ascii  "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   "
	.ascii  "                                                                "
	.ascii  "                                                                "
level2:
	.ascii	"                                                                "
	.ascii  " x                                                            x "
	.ascii  "  x                                                          x  "
	.ascii  "   x                                                        x   "
	.ascii	"    x                                                      x    "
	.ascii  "     x                                                    x     "
	.ascii  "      D                                                  d      "
	.ascii  "       D                                                d       "
	.ascii	"        D                                              d        "
	.ascii  "         x                                            x         "
	.ascii  "          x                                          x          "
	.ascii  "           x                                        x           "
	.ascii	"            x                                      x            "
	.ascii  "             x                                    x             "
	.ascii  "              d                                  D              "
	.ascii  "               d                                D               "
	.ascii	"                d                              D                "
	.ascii  "                 x                            x                 "
	.ascii  "                  x                          x                  "
	.ascii  "                   x                        x                   "
	.ascii	"                    x                      x                    "
	.ascii  "                     x                    x                     "
	.ascii  "                      D                  d                      "
	.ascii  "                       D                d                       "
	.ascii	"                        D              d                        "
	.ascii  "                         x            x                         "
	.ascii  "                          x          x                          "
	.ascii  "                           x        x                           "
	.ascii	"                            x      x                            "
	.ascii  "                             xddddx                             "
	.ascii  "                                                                "
	.ascii  "                                                                "
	.ascii	"                               s                                "
	.ascii  "                                                                "
	.ascii  "                             xDDDDx                             "
	.ascii  "                            x      x                            "
	.ascii	"                           x        x                           "
	.ascii  "                          x          x                          "
	.ascii  "                         x            x                         "
	.ascii  "                        d              D                        "
	.ascii	"                       d                D                       "
	.ascii  "                      d                  D                      "
	.ascii  "                     x                    x                     "
	.ascii  "                    x                      x                    "
	.ascii	"                   x                        x                   "
	.ascii  "                  x                          x                  "
	.ascii  "                 x                            x                 "
	.ascii  "                D                              d                "
	.ascii	"               D                                d               "
	.ascii  "              D                                  d              "
	.ascii  "             x                                    x             "
	.ascii  "            x                                      x            "
	.ascii	"           x                                        x           "
	.ascii  "          x                                          x          "
	.ascii  "         x                                            x         "
	.ascii  "        d                                              D        "
	.ascii	"       d                                                D       "
	.ascii  "      d                                                  D      "
	.ascii  "     x                                                    x     "
	.ascii  "    x                                                      x    "
	.ascii	"   x                                                        x   "
	.ascii  "  x                                                          x  "
	.ascii  " x                                                            x "
	.ascii  "                                                                "
level3:
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                                           x               "
	.ascii	"                                     x                          "
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                                           x               "
	.ascii	"                                     x                          "
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                                           x               "
	.ascii	"                                     x                          "
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                                           x               "
	.ascii	"                                     x                          "
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                                           x               "
	.ascii	"                                     x                          "
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                                           x               "
	.ascii	"                                     x                          "
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                         s                 x               "
	.ascii	"                                     x                          "
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                                           x               "
	.ascii	"                                     x                          "
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                                           x               "
	.ascii	"                                     x                          "
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                                           x               "
	.ascii	"                                     x                          "
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                                           x               "
	.ascii	"                                     x                          "
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                                           x               "
	.ascii	"                                     x                          "
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                                           x               "
	.ascii	"                                     x                          "
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                                           x               "
	.ascii	"                                     x                          "
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                                           x               "
	.ascii	"                                     x                          "
	.ascii	"                          x                                     "
	.ascii	"               x                                           x    "
	.ascii	"    x                                           x               "
	.ascii	"                                     x                          "
